childPipelines:
  scmUrls:
    - git@github.com:aishwaryanair04/external-config-child1.git
    - git@github.com:aishwaryanair04/external-config-child2.git
#     - git@github.com:aishwaryanair04/external-config-child3.git
jobs:
  main:
    image: docker.ouroath.com:4443/docker.io/node:18
    steps:
        - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET
